name: 🚀 Build, Test, and Upload on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🧑‍💻 Checkout Repository
      uses: actions/checkout@v4

    - name: 🔧 Set Up .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.x'

    - name: 📦 Restore Dependencies
      run: dotnet restore

    - name: 🏗️ Build Project
      run: dotnet build --configuration Release

    - name: 🖥️ Set up XVFB for Headless Browser
      run: |
        sudo apt-get install -y xvfb
        nohup Xvfb :99 -ac -screen 0 1280x1024x24 &

    - name: 🔐 Trust ASP.NET Core Developer Certificate
      run: dotnet dev-certs https --trust

    - name: 🌐 Install Playwright Browsers
      run: |
        npm install -g playwright
        npx playwright install

    - name: 🔧 Install Playwright CLI for .NET
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        dotnet tool update --global Microsoft.Playwright.CLI
        playwright install

    - name: 🧪 Run Tests
      run: dotnet test --configuration Release

    - name: 📦 Publish Project
      if: success()
      run: dotnet publish --configuration Release --output ./publish

    - name: 📤 Upload Published Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: published-app
        path: ./publish

  download-artifact:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: ⬇️ Download Published Artifact
      uses: actions/download-artifact@v4
      with:
        name: published-app
        path: ./downloaded-publish