name: 🚀 Run Test Code on Develop PR

on:
  pull_request:
    branches:
      - develop

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧑‍💻 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.x'

      - name: 📦 Restore Dependencies
        run: dotnet restore

      - name: 🏗️ Build Project
        run: dotnet build --no-restore

      - name: 🧪 Run Tests
        run: dotnet test --no-build --logger "trx;LogFileName=test_results.trx" --results-directory ./test-results --filter "TestCategory!=Integration"

      - name: 🔄 Convert Test Results to JUnit Format
        run: |
          dotnet tool install --global trx2junit
          trx2junit ./test-results/test_results.trx

      - name: 📑 Publish Test Results as PR Comment
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: '**/test-results/test_results.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ✅ Add Check Comments for Failed Code Lines
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/test-results/test_results.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
